# 50Hz feedback message for controls purposes
Header header

#Firmware Configuration Message: &r
#r_comm:MCU Operating Mode (RRBTX-MMOD) Channel One
#r_comm:MCU Operating Mode (RRBTX-MMOD) Channel Two
#r_comm:Brushless Operating Mode (RRBTX-BMOD) Channel One
#r_comm:Brushless Operating Mode (RRBTX-BMOD) Channel Two
#r_comm:Brushless Feedback Sensor (RRBTX-BKFB) Channel One
#r_comm:Brushless Feedback Sensor (RRBTX-BKFB) Channel Two
#r_comm:Brushless Pole Pairs (RRBTX-BPOL) Channel One
#r_comm:Brushless Pole Pairs (RRBTX-BPOL) Channel Two
#r_comm:Brushless Counter Low Limit (RRBTX-BLL) Channel One
#r_comm:Brushless Counter Low Limit (RRBTX-BLL) Channel Two
#r_comm:Brushless Counter High Limit (RRBTX-BHL) Channel One
#r_comm:Brushless Counter High Limit (RRBTX-BHL) Channel Two
#r_comm:Brushless Home Count (RRBTX-BHOME) Channel One
#r_comm:Brushless Home Count (RRBTX-BHOME) Channel One



# From the R Controller...
int32 mcu_operating_mode_channel_one
int32 mcu_operating_mode_channel_two

int32 brushless_operating_mode_channel_one
int32 brushless_operating_mode_channel_two

int32 brushless_feedback_sensor_channel_one
int32 brushless_feedback_sensor_channel_two

int32 brushless_pole_pairs_channel_one
int32 brushless_pole_pairs_channel_two

int32 brushless_counter_low_limit_channel_one
int32 brushless_counter_low_limit_channel_two

int32 brushless_counter_high_limit_channel_one
int32 brushless_counter_high_limit_channel_two

int32 brushless_home_count_channel_one
int32 brushless_home_count_channel_two




